//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customerpayment
    {
        public int PayId { get; set; }
        public string BankName { get; set; }
        public string Card_Number { get; set; }
        public string CVV { get; set; }
        public int CustId { get; set; }
    }
}
