//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrdId { get; set; }
        public string totalPrice { get; set; }
        public string Email { get; set; }
        public int CustId { get; set; }
        public string OrderStatus { get; set; }
        public string DeliveryStatus { get; set; }
        public string CustomerAddress { get; set; }
    }
}
